# Generated by Django 4.2.4 on 2023-08-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_lib', '0004_planedbooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanedBooks',
        ),
    ]
